USER-SUPPLIED VALUES:
drupalPassword: DrupalAdminPassword555
drupalSecretName: drupal-passwords-v2
drupalSecretPasswordKey: drupal-password
drupalUsername: admin
global:
  imageRegistry: docker.io
  security:
    allowInsecureImages: true
mariadb:
  auth:
    existingSecret: drupal-passwords-v2
  image:
    registry: docker.io
    repository: bitnamilegacy/mariadb
  osShell:
    image:
      registry: docker.io
      repository: bitnamilegacy/os-shell
  primary:
    persistence:
      enabled: false
  volumePermissions:
    enabled: false
persistence:
  enabled: false
service:
  type: ClusterIP
volumePermissions:
  enabled: false
