replicaCount: 1
drupalSecretName: drupal-passwords-v2
drupalSecretPasswordKey: drupal-password
drupalUsername: admin

auth:
  existingSecret: drupal-passwords-v2
  passwordKey: drupal-password
  databasePasswordKey: mariadb-password

externalDatabase:
  existingSecret: drupal-passwords-v2
  existingSecretPasswordKey: mariadb-password

drupal:
  global:
    imageRegistry: docker.io
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: bitnamilegacy/drupal
    tag: 11.2.3-debian-12-r1

  # СКРИПТ ОЖИДАНИЯ ГОТОВНОСТИ БАЗЫ ДАННЫХ
  initContainers:
    - name: wait-for-db
      image: docker.io/bitnamilegacy/os-shell:latest
      command:
        - /bin/bash
        - -ec
        - |
          echo "Waiting for MariaDB to be ready at drupal-helm-app-mariadb:3306..."
          until timeout 1 bash -c 'cat < /dev/null > /dev/tcp/drupal-helm-app-mariadb/3306' 2>/dev/null; do
            echo "Database is not reachable yet. Sleeping 5 seconds..."
            sleep 5
          done
          echo "MariaDB is UP and running!"

  auth:
    existingSecret: drupal-passwords-v2
    passwordKey: drupal-password
    databasePasswordKey: mariadb-password
  externalDatabase:
    existingSecret: drupal-passwords-v2
    existingSecretPasswordKey: mariadb-password

  persistence:
    enabled: false
  volumePermissions:
    enabled: false
  service:
    type: ClusterIP
    ports:
      http: 8080

  # Конфигурация субчарта базы данных MariaDB
  mariadb:
    # ОБЯЗАТЕЛЬНЫЙ ФЛАГ, чтобы активировать применение auth-переменных во всем чарте:
    enabled: true
    auth:
      existingSecret: drupal-passwords-v2
      passwordKey: mariadb-password
      rootPasswordKey: mariadb-root-password
    persistence:
      enabled: false
    volumePermissions:
      enabled: false
    primary:
      replicaCount: 1
      auth:
        existingSecret: drupal-passwords-v2
        passwordKey: mariadb-password
        rootPasswordKey: mariadb-root-password
      persistence:
        enabled: false
    image:
      registry: docker.io
      repository: bitnamilegacy/mariadb
      tag: 12.0.2-debian-12-r0
    osShell:
      image:
        registry: docker.io
        repository: bitnamilegacy/os-shell
