apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Удалит дочерние элементы при удалении корня
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./argo-core/
    repoURL: https://github.com/aionfiend/16.-Kubernetes.CICD.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: false
