apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-drupal
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://aionfiend.github.io/14.-Kubernetes.-Helm/
    targetRevision: 0.1.0
    chart: first-app
    helm:
      parameters:
        - name: istio.hosts[0]
          value: app-helm.k8s-1.sa
        - name: istio.hosts[1]
          value: app-helm.k8s-2.sa
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
